services:
  judgels-proxy:
    image: nginx
    container_name: judgels-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - judgels-client
      - judgels-server
    networks:
      - judgels-net
  judgels-client:
    image: ghcr.io/ia-toki/judgels/client${VERSION}
    restart: on-failure:3      
    container_name: judgels-client
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "2"
    volumes:
      - "./judgels/client/var:/judgels/client/var"
      - "./conf/judgels-client.js:/judgels/client/var/conf/judgels-client.js"
    depends_on:
      - judgels-server
    networks:
      - judgels-net
  judgels-server:
    image: ghcr.io/ia-toki/judgels/server:${VERSION}
    restart: on-failure:3
    container_name: judgels-server
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "2"
    ports:
      - "9101:9101"
    volumes:
      - "./judgels/server/var:/judgels/server/var"
      - "./conf/judgels-server.yml:/judgels/server/var/conf/judgels-server.yml"
    depends_on:
      - judgels-db
      - judgels-rabbitmq
    networks:
      - judgels-net
    environment:
      JAVA_OPTS: "" 
      JUDGELS_SERVER_APP_OPTS: >-
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/judgels/server/var/log
  judgels-db:
    image: mysql:8.4
    container_name: judgels-db
    command: mysqld --mysql-native-password=ON
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - judgels-db:/var/lib/mysql
    networks:
      - judgels-net
  judgels-rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: judgels-rabbitmq
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "2"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15671:15672"
      - "5671:5672"
    networks:
      - judgels-net

volumes:
  judgels-db:
  judgels-client:
  judgels-server:
    
networks:
  judgels-net:
    driver: bridge
